name: Package Vulnerability Scan

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory to scan for package vulnerabilities'
        required: false
        type: string
        default: '.'
    outputs:
      vulnerabilities-found:
        description: 'Whether high/critical vulnerabilities were found'
        value: ${{ jobs.scan.outputs.vulnerabilities-found }}

jobs:
  scan:
    name: Scan for Package Vulnerabilities
    runs-on: windows-latest
    outputs:
      vulnerabilities-found: ${{ steps.scan-cves.outputs.vulnerabilities-found }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Run Package Vulnerability Scan
        id: scan-cves
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          $scriptPath = ".github/scripts/CVE-Scan.ps1"
          $result = & $scriptPath -initialDirectory $pwd

          # Check if high/critical vulnerabilities were found
          $vulnerabilitiesFound = $result -match "High/Critical Vulnerabilities Found!"

          # Set output variable for other workflows
          echo "vulnerabilities-found=$vulnerabilitiesFound" >> $env:GITHUB_OUTPUT

          # Fail the job if vulnerabilities were found
          if ($vulnerabilitiesFound) {
            Write-Error "High or critical vulnerabilities were found in the solution packages."
            exit 1
          }
