name: Package Vulnerability Scan

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory to scan for package vulnerabilities'
        required: false
        type: string
        default: '.'
    outputs:
      vulnerabilities-found:
        description: 'Whether high/critical vulnerabilities were found'
        value: ${{ jobs.scan.outputs.vulnerabilities-found }}

jobs:
  scan:
    name: Scan for Package Vulnerabilities
    runs-on: windows-latest
    outputs:
      vulnerabilities-found: ${{ steps.scan-cves.outputs.vulnerabilities-found }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Pre-Scan Setup
        id: pre-scan
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          $scriptPath = ".github/scripts/Utilities.ps1"
          . $scriptPath
          Pre-Scan-Setup
      
      # - name: Run Restricted Packages Scan
        # id: scan-packages
        # shell: pwsh
        # working-directory: ${{ inputs.working-directory }}
        # run: |
        #   $scriptPath = ".github/scripts/Restricted-Packages-Scan.ps1"
        #   $result = & $scriptPath -initialDirectory $pwd
          
        #   # Check if restricted packages were found
        #   $restrictedPackagesFound = $result -match "Restricted Packages Found!"
          
        #   # Set output variable for other workflows
        #   echo "restricted-packages-found=$restrictedPackagesFound" >> $env:GITHUB_OUTPUT
          
        #   # Fail the job if restricted packages were found
        #   if ($restrictedPackagesFound) {
        #     Write-Error "Restricted packages were found in the solution."
        #     exit 1
        #   }

      - name: Run Package CVE Scan
        id: scan-cves
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          $scriptPath = ".github/scripts/CVE-Scan.ps1"
          & $scriptPath -initialDirectory $pwd

      - name: Post-Scan Teardown
        id: post-scan
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
        run: |
          $scriptPath = ".github/scripts/Utilities.ps1"
          . $scriptPath
          Post-Scan-Teardown
